### ISSUE TITLE
48-bit mode broken

### ISSUE THREAD

**Issue by DylanDC14** [Cubitect/cubiomes-viewer#76]
in cubiomes-viewer 1.11.1

when searching for something as simple as just 1 village in an area (-200,-200),(200,200) it finds only 1 seed every 2 seconds on 8 threads.

It's also give me way more lag than cubiomes-viewer 1.9.1

It also only seems to find seeds with the top 16 bits all 1's

**Comment by Cubitect** [comment]
This bug was introduced together with the relative condition system, and should hopefully be fixed now.

**Comment by DylanDC14** [comment]
im pretty sure it still doesnt work as intended

It only prints out seeds if the seed with the same lower 48 bits + 16 "0" top bits meets the set requirement aswell

so only finds seeds if the structureseed itself meets the requirements aswell

**Comment by Cubitect** [comment]
This should hopefully be fixed a little better now.

**Comment by DylanDC14** [comment]
seems to work as expected now! nice job on the quick 1.18 release btw! nice to be able to quickly find some interesting seeds.
